# Generated by Django 5.2.13 on 2026-04-26 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64)),
                ('type_id', models.CharField(blank=True, max_length=64)),
                ('badge', models.CharField(blank=True, max_length=64)),
                ('color_class', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(blank=True, default='#', max_length=512)),
                ('role', models.CharField(blank=True, max_length=512)),
                ('desc', models.TextField(blank=True)),
                ('links', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_document_owner_slug')],
            },
        ),
    ]
