# Generated by Django 5.2.13 on 2026-04-26 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_color_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hierarchy', 'Hierarchy'), ('decisionFlow', 'Decision Flow'), ('form1Fields', 'Form 1 Fields'), ('form2Fields', 'Form 2 Fields'), ('form3Fields', 'Form 3 Fields'), ('reviewTurnbacks', 'Review Turnbacks'), ('reviewRefMeta', 'Review Ref Meta'), ('descriptions', 'Descriptions'), ('specialChars', 'Special Chars')], max_length=32)),
                ('data', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'kind'), name='uniq_catalog_owner_kind')],
            },
        ),
    ]
